---
title: "EcuadorPlantStackedSpeciesMaps"
author: "Hazel Anderson"
date: "6/30/2020"
describtion: This script takes BIEN species range maps and uses them to create a map of species richness of Ecuador plant species.
output:
  pdf_document: default
  html_document: default
---

# Load required packages
```{r}
library(BIEN)
library(ape)
library(maps)
library(sp)
library(sf)
library(dplyr)
library(ggplot2)
library(scico)
library(rnaturalearth)
library(purrr)
library(smoothr)
library(maptools)
library(lwgeom)
library(rgeos)
library(rgdal)

```


# Species Maps for All Ecuador Species
```{r}
setwd("C:/Users/hj152/Documents/R/SpatialMap")

if (file.exists("Ecuador_plant_range_maps_workspace.RData")){
    load("~/R/SpatialMap/Ecuador_plant_range_maps_workspace.RData")
}else {
    #List of Ecuador Species
    Ecuador <- BIEN_occurrence_country("Ecuador")
    Ecuador_species_list <- unique(Ecuador$scrubbed_species_binomial)
    write.csv(Ecuador_species_list, "Ecuador_species_list.csv")
    
    #Species Maps for all plant species in Ecuador
    Ecuador_plant_species_list_vector <- pull(Ecuador_species_list, x)
    Ecuador_plant_range_maps <- BIEN_ranges_load_species(species = Ecuador_plant_species_list_vector)
    
    #Save workspace
    save.image("~/R/SpatialMap/Ecuador_plant_range_maps_workspace.RData")
}
```

# Merge Ecuador plant species list with range map list
```{r}
checked_list <- merge(Ecuador_species_list, Ecuador_plant_range_maps)
print(checked_list)
```

# Pull shapefiles for Ecuador plants
```{r}
Ecuador_plants <- st_as_sf(Ecuador_plant_range_maps)
```

# Load in world map
```{r}
worldMap <- ne_countries(scale = "medium", type = "countries", returnclass = "sf")

# country subset. In this case we are removing the Galapagos by defining the bounding box around the Ecuador polygon.
CRpoly <- worldMap %>% filter(sovereignt == "Ecuador")
ecuador_shp <-st_crop(CRpoly, c(xmin=-84, xmax=-75.24961, ymin=-4.990625, ymax=1.455371))

# trim the map to appropriate study area. This zooms out of Ecuador, which will be easier for visualization down the line.
limsCR <- st_buffer(ecuador_shp, dist = 9) %>% st_bbox()

# neighboring countries (will include Colombia as well)
adjacentPolys <- st_touches(ecuador_shp, worldMap)
neighbours <- worldMap %>% slice(pluck(adjacentPolys, 1))

# countries
divpolPlot <-
ggplot() +
geom_sf(data = neighbours, color = "white") +
geom_sf(data = ecuador_shp) +
coord_sf(
xlim = c(limsCR["xmin"], limsCR["xmax"]),
ylim = c(limsCR["ymin"], limsCR["ymax"])
) +
scale_x_continuous(breaks = c(-84)) +
theme(
plot.background = element_rect(fill = "#f1f2f3"),
panel.background = element_rect(fill = "#2F4051"),
panel.grid = element_blank(),
line = element_blank(),
rect = element_blank()
)
divpolPlot
```

# Plot hulls
```{r}
hullsPlot <-
ggplot() +
geom_sf(data = neighbours, color = "white") +
geom_sf(data = ecuador_shp) +
geom_sf(data = Ecuador_plants, aes(fill = species), alpha = 0.7) +
scale_fill_scico_d(palette = "davos", direction = -1, end = 0.9, guide = FALSE) +
coord_sf(
xlim = c(limsCR["xmin"], limsCR["xmax"]),
ylim = c(limsCR["ymin"], limsCR["ymax"])
) +
scale_x_continuous(breaks = c(-84)) +
theme(
plot.background = element_rect(fill = "#f1f2f3"),
panel.background = element_rect(fill = "#2F4051"),
panel.grid = element_blank(),
line = element_blank(),
rect = element_blank()
)
hullsPlot

```

# Define a grid
```{r}
CRGrid <- ecuador_shp %>%
st_make_grid(cellsize = 0.2) %>%
st_intersection(ecuador_shp) %>%
st_cast("MULTIPOLYGON") %>%
st_sf() %>%
mutate(cellid = row_number())
```

# Richness for convex hulls
```{r}
richness_gridEOO <- CRGrid %>%
st_join(Ecuador_plants) %>%
mutate(overlap = ifelse(!is.na(id), 1, 0)) %>%
group_by(cellid) %>%
summarize(num_species = sum(overlap))
```

# Empty grid, more detailed in nature
```{r}
gridPlot <-
ggplot() +
geom_sf(data = neighbours, color = "white") +
geom_sf(data =ecuador_shp) +
geom_sf(data = CRGrid) +
coord_sf(
xlim = c(limsCR["xmin"], limsCR["xmax"]),
ylim = c(limsCR["ymin"], limsCR["ymax"])
) +
scale_x_continuous(breaks = c(-84)) +
theme(
plot.background = element_rect(fill = "#f1f2f3"),
panel.background = element_rect(fill = "#2F4051"),
panel.grid = element_blank(),
line = element_blank(),
rect = element_blank()
)
gridPlot
```

# Richness for convex hulls, more detailed
```{r}
gridRichCR_eoo <-
ggplot(richness_gridEOO) +
geom_sf(data = neighbours, color = "white") +
geom_sf(data = ecuador_shp, fill = "grey", size = 0.1) +
geom_sf(aes(fill = num_species), color = NA) +
scale_fill_scico(palette = "davos", direction = -1, end = 0.9) +
coord_sf(
xlim = c(limsCR["xmin"], limsCR["xmax"]),
ylim = c(limsCR["ymin"], limsCR["ymax"])
) +
scale_x_continuous(breaks = c(-84)) +
theme(
plot.background = element_rect(fill = "#f1f2f3"),
panel.background = element_rect(fill = "#2F4051"),
panel.grid = element_blank(),
line = element_blank(),
rect = element_blank()
) + labs(fill = "richness")
gridRichCR_eoo

```

