---
title: 'Frugivoria: Ecuadorian Birds & Mammals richness'
author: "Beth E. Gerstner"
date: "7/7/2020"
output:
  pdf_document: default
  html_document: default
description: This script is part of the overarching Frugivoria project, which aims
  to build a comprehensive database of functional traits for birds and mammals (frugivores)
  in Central and South American tropical forests. This smaller project focuses on
  birds and mammals in Ecuador and will eventually be used to understand plant/animal
  interactions. Specifically, this script takes IUCN range maps and stacks them, allowing
  us to summarize taxonomic richness based on ranges. (Currently only works with mammals,
  but will have birds done shortly.)
---
```{r}
library(sf)
library(dplyr)
library(ggplot2)
library(scico)
library(rnaturalearth)
library(purrr)
library(smoothr)
library(rgbif)
library(lwgeom)
```

# Load packages
```{r}
library(sf)
library(rgeos)
library(rgdal)
```

# Pull shapefiles for frugivorous species (only mammals at this point)
```{r}
setwd("/Users/bethgerstner/Desktop/MSU/Zarnetske_Lab/Data/IUCN_Data/TERRESTRIAL_MAMMALS/TERRESTRIAL_MAMMALS_1")
IUCN_mam <-read_sf("/Users/bethgerstner/Desktop/MSU/Zarnetske_Lab/Data/IUCN_Data/TERRESTRIAL_MAMMALS_2/TERRESTRIAL_MAMMALS.shp")
mam_frug_ec <- read.csv("/Users/bethgerstner/Desktop/MSU/Zarnetske_Lab/Data/Elton_Traits_birds_mammals/Ecuador_species/mam_frug_ec.csv")
```

# Subset IUCN mammal shapefile by: creating new column in the shapefile so that each shapefile has a unique identifier 
```{r}
IUCN_mam$new_id = 1:nrow(IUCN_mam)

# list of unique species names for frugivorous mammals in Ecuador made above

mam_frug_sn <-as.vector(unique(mam_frug_ec$IUCN_species_name))

# Subset the new IDs made above by those that have species names matching the frugivorous subset
shapes  = IUCN_mam$new_id[IUCN_mam$binomial %in% mam_frug_sn] # shapes = ID numbers for subset

# Subsets the IUCN shapefiles to those with IDs matching the frugivorous subset
IUCN_mam_df = IUCN_mam[IUCN_mam$new_id %in% shapes,] #268 shapefiles for species list (209 species)

#write the shapefile to a file
#setwd("/Users/bethgerstner/Desktop/MSU/Zarnetske_Lab/Data/Elton_Traits_birds_mammals/mx_species")
#st_write(IUCN_mam_df, "ec_mammals.shp")
```

# Load in a world map
```{r}
worldMap <- ne_countries(scale = "medium", type = "countries", returnclass = "sf")

# country subset. In this case we are removing the Galapagos by defining the bounding box around the Ecuador polygon.
CRpoly <- worldMap %>% filter(sovereignt == "Ecuador")
ecuador_shp <-st_crop(CRpoly, c(xmin=-84, xmax=-75.24961, ymin=-4.990625, ymax=1.455371))
```

```{r}
# trim the map to appropriate study area. This zooms out of Ecuador, which will be easier for visualization down the line.
limsCR <- st_buffer(ecuador_shp, dist = 9) %>% st_bbox()

# neighboring countries (will include Colombia as well)
adjacentPolys <- st_touches(ecuador_shp, worldMap)
neighbours <- worldMap %>% slice(pluck(adjacentPolys, 1))

# countries
divpolPlot <-
  ggplot() +
  geom_sf(data = neighbours, color = "white") +
  geom_sf(data = ecuador_shp) +
  coord_sf(
    xlim = c(limsCR["xmin"], limsCR["xmax"]),
    ylim = c(limsCR["ymin"], limsCR["ymax"])
  ) +
  scale_x_continuous(breaks = c(-84)) +
  theme(
    plot.background = element_rect(fill = "#f1f2f3"),
    panel.background = element_rect(fill = "#2F4051"),
    panel.grid = element_blank(),
    line = element_blank(),
    rect = element_blank()
  )
divpolPlot
```
# plot hulls
```{r}
hullsPlot <-
  ggplot() +
  geom_sf(data = neighbours, color = "white") +
  geom_sf(data = ecuador_shp) +
  geom_sf(data = IUCN_mam_df, aes(fill = binomial), alpha = 0.7) +
  scale_fill_scico_d(palette = "davos", direction = -1, end = 0.9, guide = FALSE) +
  coord_sf(
    xlim = c(limsCR["xmin"], limsCR["xmax"]),
    ylim = c(limsCR["ymin"], limsCR["ymax"])
  ) +
  scale_x_continuous(breaks = c(-84)) +
  theme(
    plot.background = element_rect(fill = "#f1f2f3"),
    panel.background = element_rect(fill = "#2F4051"),
    panel.grid = element_blank(),
    line = element_blank(),
    rect = element_blank()
  )
hullsPlot
```

# define a grid
```{r}
CRGrid <- ecuador_shp %>%
  st_make_grid(cellsize = 0.2) %>%
  st_intersection(ecuador_shp) %>%
  st_cast("MULTIPOLYGON") %>%
  st_sf() %>%
  mutate(cellid = row_number())
```

# richness for convex hulls
```{r}
richness_gridEOO <- CRGrid %>%
  st_join(IUCN_mam_df) %>%
  mutate(overlap = ifelse(!is.na(id), 1, 0)) %>%
  group_by(cellid) %>%
  summarize(num_species = sum(overlap))
```
# empty grid, more detailed in nature
```{r}
gridPlot <-
  ggplot() +
  geom_sf(data = neighbours, color = "white") +
  geom_sf(data =ecuador_shp) +
  geom_sf(data = CRGrid) +
  coord_sf(
    xlim = c(limsCR["xmin"], limsCR["xmax"]),
    ylim = c(limsCR["ymin"], limsCR["ymax"])
  ) +
  scale_x_continuous(breaks = c(-84)) +
  theme(
    plot.background = element_rect(fill = "#f1f2f3"),
    panel.background = element_rect(fill = "#2F4051"),
    panel.grid = element_blank(),
    line = element_blank(),
    rect = element_blank()
  )
gridPlot
```


# richness for convex hulls, more detailed
```{r}
gridRichCR_eoo <-
  ggplot(richness_gridEOO) +
  geom_sf(data = neighbours, color = "white") +
  geom_sf(data = ecuador_shp, fill = "grey", size = 0.1) +
  geom_sf(aes(fill = num_species), color = NA) +
  scale_fill_scico(palette = "davos", direction = -1, end = 0.9) +
  coord_sf(
    xlim = c(limsCR["xmin"], limsCR["xmax"]),
    ylim = c(limsCR["ymin"], limsCR["ymax"])
  ) +
  scale_x_continuous(breaks = c(-84)) +
  theme(
    plot.background = element_rect(fill = "#f1f2f3"),
    panel.background = element_rect(fill = "#2F4051"),
    panel.grid = element_blank(),
    line = element_blank(),
    rect = element_blank()
  ) + labs(fill = "richness")
gridRichCR_eoo
```
