---
title: 'Frugivoria: Ecuadorian Birds, Mammals, and Plants'
author: "Beth Gerstner & Hazel Anderson"
date: "6/1/2020"
output:
  pdf_document: default
  html_document: default
---
# Load packages and IUCN API
```{r, message=FALSE}
library(httr) 
library(jsonlite)
library(dplyr)
library(rredlist) 

api_url <- 'https://apiv3.iucnredlist.org/api/v3/'
token <- '3b3db1c753a7cad0616e16146363ec88eead97d185cb3304070d7343123516fd'
```

# Pull in Ecuadorian species from IUCN Redlist
```{r}
#Ecuador
ecuador_species <- rl_sp_country("EC", key = token, parse = TRUE)
c1 <- ecuador_species$result[1]

```

# Break down by species group for the world (will subset to Ecuadorian species)
```{r}

# Get codes for the birds
all_birds <-rl_comp_groups(group = c('birds'), key = token)

# Get codes for the mammals
all_mammals <-rl_comp_groups(group = c('mammals'), key = token)

```

# Mammals and birds occurring in Ecuador _ testing one more time
```{r}

#Mammals

ec_mammals <- merge(all_mammals$result, c1, by="taxonid")

#Birds
ec_birds <- merge(all_birds$result, c1, by="taxonid")
```



#____________________________________________________________________________________________
#### Hazel start your code here! I'll continue adding above